name: Auto Fix & Heal
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  heal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci || npm i
      - name: Auto-fix + Clean + Check
        run: npm run ci:heal
        env:
          AMAZON_TAG: "TON_TAG"
      - name: Commit fixes
        run: |
          git config user.name "autofix-bot"
          git config user.email "bot@example.com"
          git add -A
          git commit -m "chore(auto-fix): heal site structure & posts" || echo "nothing to commit"
          git push
